vednn

diff --git a/vednn.patch b/vednn.patch
--- a/vednn.patch
+++ b/vednn.patch
@@ -22,18 +22,18 @@
  usage() {
      echo "$0 usage:"
      #head -n 30 "$0" | grep "^[^#]*.)\ #"
-@@ -225,8 +226,8 @@
+@@ -225,8 +226,9 @@
  if [ ${DOJUSTDOC} -gt 0 ]; then
      echo " JUST building doxygen docs"
  fi
--INSTALLDIR=install
++GENERIC_INSTALLDIR=${VEDNN_INSTALL_DIR:-vednn-install}
+ INSTALLDIR=install
 -BUILDDIR=build
-+INSTALLDIR=${VEDNN_INSTALL_DIR:-install}
 +BUILDDIR=${VEDNN_BUILD_DIR:-build}
  #
  # I have not yet tried icc.
  # we MUST avoid the full MKL (omp issues) (mkldnn uses the mkl subset in external/)
-@@ -246,8 +247,14 @@
+@@ -246,8 +248,14 @@
  #
  if [ "$DOTARGET" == "s" ]; then DODOC="n"; DOTEST=0; INSTALLDIR='install-sx'; BUILDDIR='build-sx';
  elif [ "$DOTARGET" == "a" ]; then
@@ -50,43 +50,43 @@
      fi
  else #if [ "$DOTARGET" != "a" ]; then
      if [ "$DOGCC_VER" == "icc" ]; then
-@@ -305,7 +312,7 @@
+@@ -305,7 +313,7 @@
          if [ ! -d build ]; then mkdir build; fi
          if [ ! -f build/Doxyfile ]; then
              # doxygen does not much care HOW to build, just WHERE
 -            (cd build && cmake -DCMAKE_INSTALL_PREFIX=../${INSTALLDIR} -DFAIL_WITHOUT_MKL=OFF ..)
-+            (cd build && cmake -DCMAKE_INSTALL_PREFIX=${INSTALLDIR} -DDNNL_BUILD_TESTS=0  -DFAIL_WITHOUT_MKL=OFF ..)
++            (cd build && cmake -DCMAKE_INSTALL_PREFIX=${GENERIC_INSTALLDIR}  -DDNNL_LIBRARY_TYPE=STATIC -DDNNL_BUILD_TESTS=0  -DFAIL_WITHOUT_MKL=OFF ..)
          fi
          echo "Doxygen (please be patient) logging to doxygen.log"
          rm -f build/doc*stamp
-@@ -336,7 +343,7 @@
+@@ -336,7 +344,7 @@
          if [ ! -d build ]; then mkdir build; fi
          if [ ! -f build/Doxyfile ]; then
              # doxygen does not much care HOW to build, just WHERE
 -            (cd build && cmake -DCMAKE_INSTALL_PREFIX=../${INSTALLDIR} -DFAIL_WITHOUT_MKL=OFF ..)
-+            (cd build && cmake -DCMAKE_INSTALL_PREFIX=${INSTALLDIR} -DDNNL_BUILD_TESTS=0  -DFAIL_WITHOUT_MKL=OFF ..)
++            (cd build && cmake -DCMAKE_INSTALL_PREFIX=${GENERIC_INSTALLDIR}  -DDNNL_LIBRARY_TYPE=STATIC -DDNNL_BUILD_TESTS=0  -DFAIL_WITHOUT_MKL=OFF ..)
          fi
          echo "Doxygen (please be patient) logging to doxygen-full.log"
          rm -f build/doc*stamp-full
-@@ -499,7 +506,7 @@
+@@ -499,7 +507,7 @@
          ccxx_flags "${DOWARNFLAGS}"
      fi
      OPT_FLAGS=
 -    CMAKEOPT="${CMAKEOPT} -DCMAKE_INSTALL_PREFIX=../${INSTALLDIR}"
-+    CMAKEOPT="${CMAKEOPT} -DCMAKE_INSTALL_PREFIX=${INSTALLDIR} -DDNNL_BUILD_TESTS=0 "
++    CMAKEOPT="${CMAKEOPT} -DCMAKE_INSTALL_PREFIX=${GENERIC_INSTALLDIR}  -DDNNL_LIBRARY_TYPE=STATIC -DDNNL_BUILD_TESTS=0 "
      if [ $DODEBUG -eq 0 ]; then
          CMAKEOPT="${CMAKEOPT} -DCMAKE_BUILD_TYPE=Release"
      elif [ $DODEBUG -eq 1 ]; then
-@@ -647,7 +654,7 @@
+@@ -647,7 +655,7 @@
  
          # adjust here for VE shared library and Openmp use
          #CMAKEOPT="${CMAKEOPT} -DUSE_SHAREDLIB=OFF" # deprecated
 -        #CMAKEOPT="${CMAKEOPT} -DDNNL_LIBRARY_TYPE=STATIC"
-+        CMAKEOPT="${CMAKEOPT} -DDNNL_LIBRARY_TYPE=STATIC -DDNNL_BUILD_TESTS=0 "
++        CMAKEOPT="${CMAKEOPT} -DDNNL_LIBRARY_TYPE=STATIC  -DDNNL_LIBRARY_TYPE=STATIC -DDNNL_BUILD_TESTS=0 "
          #CMAKEOPT="${CMAKEOPT} -DDNNL_LIBRARY_TYPE=SHARED" # default
  
          # USE_OPENMP defaults to off, so force it on (VE openmp has improved)
-@@ -802,7 +809,7 @@
+@@ -802,7 +810,7 @@
      #        ve_validate_binary -d "${BUILDDIR}/${d}"
      #    done
      #fi
@@ -95,6 +95,11 @@
          echo "DOTARGET  $DOTARGET"
          echo "ISA       $ISA"
          echo "DOTEST    $DOTEST"
+@@ -1102,3 +1110,4 @@
+ # Return value is BUILDOK (so repeat-build scripts can stop on success)
+ if [ "${BUILDOK}" == "y" ]; then exit 0; fi
+ exit 1 # error
++
 --- src/cpu/simple_q10n.hpp	2021-12-06 04:44:23.166824100 +0400
 +++ src/cpu/simple_q10n_new.hpp	2021-12-06 08:07:01.116980900 +0400
 @@ -36,7 +36,7 @@
@@ -106,3 +111,4 @@
  #if DNNL_X64
      return _mm_cvtss_si32(_mm_load_ss(&f));
  #elif defined(__ve)
+ 
